name: Build and Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Build and Test
        run: |
          chmod +x gradlew
          ./gradlew build
